import "@radix-ui/themes/styles.css";
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from "@radix-ui/themes"
import Navbar from './Navbar/NavBar'
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from "./context/AuthContext";
import ProtectedRoute from "./ProtectedRoute/ProtectedRoute";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="violet">
          <ProtectedRoute>
            <Navbar/>
          </ProtectedRoute>
          <main className="p-5">{children}</main>
          <ToastContainer/>
        </Theme>
      </body>
    </html>
    </AuthProvider>
  )
}
